- name: copy global gitignore
  copy: 
    src: files/.gitignore_global
    dest: ~/.gitignore_global
- name: set git username
  git_config:
    name: user.name
    scope: global
    value: Jacob See
- name: set git email
  git_config:
    name: user.email
    scope: global
    value: jacob.d.see@gmail.com
- name: set git ignore file
  git_config:
    name: core.excludesfile
    scope: global
    value: "{{ ansible_env.HOME }}/.gitignore_global"
- name: display signed commit info
  debug:
    msg: "This playbook does not set up signed commits. Please see https://help.github.com/categories/authenticating-to-github/ for that, and don't forget `git config --global gpg.program gpg2` if the gpg2 tool is used instead."